on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: discord commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send message to discord
        uses: ./ # Uses an action in the root directory
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "hello world"
          commit: "{ title: "asdf" }"
